### ISSUE TITLE
ValueError: Received invalid argument(s): edgewidth

### ISSUE THREAD

**Issue by zzwonder** [syanga/dglearn#1]
Hi there,

I was trying to use dglearn and running the python examples (graph_learning.py and graph_enumeration.py). However they ended up with error "Received invalid argument(s): edgewidths" as follows. Do you have any clue why this happening? Thanks!

`Traceback (most recent call last):
  File "graph_enumeration.py", line 17, in <module>
    node_size=800, font_size=16, width=2.5, connectionstyle='arc3,rad=0.15', node_color='skyblue')
  File "../dglearn/plotter/plot_dg.py", line 26, in plot_structure
    labels=name_dict, node_size=node_size, font_size=font_size, width=width, node_color=node_color, edgecolors='k', edgewidths=4, connectionstyle=connectionstyle)
  File "/home/user/.local/lib/python3.7/site-packages/networkx/drawing/nx_pylab.py", line 121, in draw
    draw_networkx(G, pos=pos, ax=ax, **kwds)
  File "/home/user/.local/lib/python3.7/site-packages/networkx/drawing/nx_pylab.py", line 324, in draw_networkx
    raise ValueError(f"Received invalid argument(s): {invalid_args}")
ValueError: Received invalid argument(s): edgewidths`

**Comment by syanga** [comment]
Hey,

It appears that edgewidth is no longer an argument used by networkx.draw. I have removed it from the plotting code, and the examples should run now -- let me know if there are any other issues. 

Thanks!
